# Generated by Django 5.2.1 on 2025-06-06 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('personal', '0001_initial'),
        ('sangre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombsDirecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CombsIndirecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GradoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_emergencia', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=10)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=10)),
                ('grado_emergencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transfusiones.gradoemergencia')),
            ],
        ),
        migrations.CreateModel(
            name='Transfusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('material1', models.CharField(max_length=5)),
                ('material2', models.CharField(max_length=5)),
                ('material3', models.CharField(max_length=5)),
                ('material4', models.CharField(max_length=5)),
                ('material5', models.CharField(max_length=5)),
                ('numero_tratamiento1', models.CharField(max_length=50)),
                ('numero_tratamiento2', models.CharField(max_length=50)),
                ('comb_directo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transfusiones.combsdirecto')),
                ('comb_indirecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transfusiones.combsindirecto')),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transfusiones.diagnostico')),
                ('hemocomponente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sangre.hemocomponente')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.medico')),
                ('observacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transfusiones.observacion')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.paciente')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.responsable')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transfusiones.unidad')),
            ],
        ),
    ]
